name: flutter_statix
description: A simple CLI tool that automatically runs flutter test — ideal for use in CI/CD pipelines or as a pre-launch step.
version: 1.0.8
homepage: https://github.com/adinath-nikam/flutter_statix
repository: https://github.com/adinath-nikam/flutter_statix

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  analyzer: ^6.0.0
  path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  flutter_statix: flutter_statix
#  dart_parser: dart_parser.dart
#  generate_html: generate_html_report.dart
#  dart_metrics: dart_metrics.dart
#  dart_analysis: dart_analyzer.dart
#  send_mail: send_email.dart
